# Generated by Django 3.0.3 on 2021-08-10 22:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderHeader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orduniq', models.DecimalField(decimal_places=0, max_digits=19)),
                ('ordnumber', models.CharField(max_length=22)),
                ('customer', models.CharField(max_length=12)),
                ('orderdate', models.DecimalField(decimal_places=0, max_digits=9)),
                ('expirydate', models.DecimalField(decimal_places=0, max_digits=9)),
            ],
        ),
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('linenumber', models.IntegerField()),
                ('itemnumber', models.CharField(max_length=24)),
                ('orderedquantity', models.DecimalField(decimal_places=4, max_digits=19)),
                ('committedquantity', models.DecimalField(decimal_places=4, max_digits=19)),
                ('orderheader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orderdetails', to='blog.OrderHeader')),
            ],
        ),
    ]
