# Generated by Django 3.0.3 on 2021-08-11 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20210810_1936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bintransfer',
            name='comment',
            field=models.CharField(default='a', max_length=250),
        ),
        migrations.AlterField(
            model_name='bintransfer',
            name='destbin',
            field=models.CharField(default='a', max_length=10),
        ),
        migrations.AlterField(
            model_name='bintransfer',
            name='destloc',
            field=models.CharField(default='a', max_length=6),
        ),
        migrations.AlterField(
            model_name='bintransfer',
            name='doctype',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='bintransfer',
            name='itemdesc',
            field=models.CharField(default='a', max_length=60),
        ),
        migrations.AlterField(
            model_name='bintransfer',
            name='itemno',
            field=models.CharField(default='a', max_length=24),
        ),
        migrations.AlterField(
            model_name='bintransfer',
            name='srcbin',
            field=models.CharField(default='a', max_length=10),
        ),
        migrations.AlterField(
            model_name='bintransfer',
            name='srcloc',
            field=models.CharField(default='a', max_length=6),
        ),
        migrations.AlterField(
            model_name='bintransfer',
            name='srctype',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='bintransfer',
            name='time',
            field=models.DecimalField(decimal_places=0, default=1, max_digits=9),
        ),
    ]
