# Generated by Django 3.0.3 on 2021-08-21 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20210811_1055'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload', models.FileField(upload_to='uploads/')),
            ],
        ),
        migrations.AlterField(
            model_name='bintransfer',
            name='comment',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='bintransfer',
            name='destbin',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='bintransfer',
            name='destloc',
            field=models.CharField(blank=True, default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='bintransfer',
            name='doctype',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='bintransfer',
            name='itemdesc',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
        migrations.AlterField(
            model_name='bintransfer',
            name='itemno',
            field=models.CharField(blank=True, default='', max_length=24),
        ),
        migrations.AlterField(
            model_name='bintransfer',
            name='quantitytran',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=19),
        ),
        migrations.AlterField(
            model_name='bintransfer',
            name='srcbin',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='bintransfer',
            name='srcloc',
            field=models.CharField(blank=True, default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='bintransfer',
            name='srctype',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='bintransfer',
            name='time',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=9),
        ),
    ]
