# Generated by Django 3.0.3 on 2021-08-21 22:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20210821_1253'),
    ]

    operations = [
        migrations.AddField(
            model_name='mymodel',
            name='orderheader',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='mymodel', to='blog.OrderHeader'),
        ),
    ]
