# Generated by Django 3.0.3 on 2021-08-21 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20210821_1521'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderheader',
            name='mymodel',
        ),
    ]
