# Generated by Django 3.0.3 on 2021-08-22 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_auto_20210821_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mymodel',
            name='upload',
            field=models.FileField(upload_to='media/'),
        ),
    ]
