# Generated by Django 3.0.3 on 2021-08-22 02:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_auto_20210821_1829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mymodel',
            name='orderheader',
            field=models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mymodel', to='blog.OrderHeader', to_field='ordnumber'),
        ),
        migrations.AlterField(
            model_name='orderheader',
            name='ordnumber',
            field=models.CharField(max_length=22, unique=True),
        ),
    ]
