# Generated by Django 3.0.3 on 2021-08-22 03:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_auto_20210821_1943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mymodel',
            name='orderheader',
            field=models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mymodel', to='blog.OrderHeader'),
        ),
    ]
