# Generated by Django 3.0.3 on 2021-08-22 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_auto_20210821_2022'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderheader',
            name='pod',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
    ]
