# Generated by Django 3.0.3 on 2021-08-23 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_orderheader_pod'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderheader',
            name='submit',
            field=models.CharField(blank=True, default='Submit', max_length=10),
        ),
    ]
