# Generated by Django 3.0.3 on 2021-09-14 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0022_customuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdjustmentLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reserved_sku', models.CharField(blank=True, default='', max_length=30)),
                ('reserved_desc', models.CharField(blank=True, default='', max_length=30)),
                ('reserved_quant', models.CharField(max_length=9)),
                ('optima_sku', models.CharField(blank=True, default='', max_length=10)),
                ('optima_desc', models.CharField(blank=True, default='', max_length=10)),
                ('optima_quant', models.DecimalField(decimal_places=0, max_digits=9)),
                ('in_transit_quant', models.DecimalField(decimal_places=0, max_digits=9)),
                ('transfer_quant', models.DecimalField(decimal_places=0, max_digits=9)),
            ],
        ),
    ]
