# Generated by Django 3.0.3 on 2021-09-14 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0023_adjustmentline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adjustmentline',
            name='transfer_quant',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=9),
        ),
    ]
