# Generated by Django 3.0.3 on 2021-09-14 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0024_auto_20210913_2309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adjustmentline',
            name='optima_desc',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='adjustmentline',
            name='optima_sku',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
    ]
